### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by EvaFlower** [lfovia/QAGANS#2]
Hi there,

Interesting work! Is it possible to share your trained model?

**Comment by lfovia** [comment]
Hi,
Our servers are down due to lockdown. 
We will update you the Trained models for all the datasets soon.
For now , we are providing our models for CelebA dataset. https://drive.google.com/drive/folders/1pRefrLoWRoYR1YLfgCYW5cwmIuczMwrW?usp=sharing
We will update  again. Thanks.

**Comment by EvaFlower** [comment]
Thanks a lot for your quick reply.

However, there is an exception when running generate_more_image.py with the trained model. I have followed the instruction to revise the architecture and dir. The error is as follows:
`OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key generator/BatchNorm/beta not found in checkpoint`

And when running celebA_SSIM_GP.py, there is the error as follows:
```
Traceback (most recent call last):
  File "celebA_SSIM_GP.py", line 309, in <module>
    _, d_loss_result = sess.run([d_train, d_loss])
  File "/data/yinyao/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/data/yinyao/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/yinyao/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/data/yinyao/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: FIFOQueue '_2_placeholders/batch/fifo_queue' is closed and has insufficient elements (requested 64, current size 39)
         [[node placeholders/batch (defined at celebA_SSIM_GP.py:72) ]]
         [[placeholders/mul/_5]]
  (1) Out of range: FIFOQueue '_2_placeholders/batch/fifo_queue' is closed and has insufficient elements (requested 64, current size 39)
         [[node placeholders/batch (defined at celebA_SSIM_GP.py:72) ]]
0 successful operations.
0 derived errors ignored.
```

I appreciate any help from you!

**Comment by lfovia** [comment]
Hi, 
 It was a variable names mismatch error.  Can you please use the reloading.py uploaded in the drive.we will again upload the models compatible with previous code soon. Please wait for the models. Thanks.

**Comment by EvaFlower** [comment]
Thanks a lot! It worked. The other problem is due to the data mistake.
